In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats
import math
from matplotlib import pyplot as plt
#To calculate area below the normal distribution and calculate probabilities
from numpy import trapz 
from scipy.integrate import simps

# ANOVA: Exercise 1

Researchers want to test a new anti-anxiety medication. They split participants into three conditions (0mg, 50mg and 100mg), then ask them to rate their anxiety level on a scale from 1 to 10. Are there any differences between the three conditions using alpha = 0.05.

(Source: [YouTube Course](https://www.youtube.com/watch?v=51QZa7b0Ozk))

### Answer:

So, from what I'm understanding here, this test is about comparing more than 2 groups. The null hypothesis is to say that the mean of the 3 groups in this exercise are equals. More specifically, we're saying that the values of the 3 samples don't differ enough to be able to assert that the medication actually have an effect on the condition to cure...

***With that being said:***
h_1 is saying that these means are not equals. So it's a little bit like the previous Z test we done when comparing two averages the main difference here, is that you're comparing more than just 2 groups...

As usual, we set alpha to 5%

In [3]:
# First step: create the dataset:
df = pd.DataFrame({'0mg':[9,8,7,8,8,9,8], '50mg':[7,6,6,7,8,7,6], '100mg':[4,3,2,3,4,3,2]})
df

   0mg  50mg  100mg
0    9     7      4
1    8     6      3
2    7     6      2
3    8     7      3
4    8     8      4
5    9     7      3
6    8     6      2

### The aim is to fill out the tab below to then we'll see how to use it to validate/invalidate our hypothesis...

In [23]:
# We're trying to fill out the following tab:
dfDemo = pd.DataFrame({'SS':[" "," "," "], 'df':[" "," "," "], 'MS':[" "," "," "], 'F':[" "," "," "]}, index = ["Between", "Within", "Total"])
dfDemo

        SS df MS  F
Between
Within
Total

Quick hint: We're looking for the F statitstic (last field of the tab). We'll find it using the tab's other fields which formulas can be found below. The plan here is that, once we get the F statistic, we compare it to a "critical value" (I'll define what this is shortltly). If F is greater than the critical value, then we can reject the null hypothesis that states that the variations we see in our dataset come from the randomness of the experiment...

The critical value is calculated using alpha (like in every previous hypothses tests we've ran before). Here, we'll be using a table to lookup for that critical value. Check what is happening below for more detail:

[TO DO] Add a descritption of the meaning of the different fields and their formulas (use the YT video if necessary...)

In [24]:
# The first step of the ANOVA (once we got all the parameters from above) is to calculate the degrees of freedom
    # Degrees of freedom between = a - 1
    # Degrees of freedom within = N - a
    # Degrees of freedom total = N - 1
    # with "N" (capital N) being the total number of values in your dataset, "n" (small "n") being the number of values per columns and a being the number of columns/variables in your dataset...

# So in our example:
N = df.shape[0]*df.shape[1]
n = df.shape[0]
a = df.shape[1]

# Let's just write small functions to calculate those values:

def df_between(df):
    res = df.shape[1] - 1
    return res

def df_within(df):
    res = df.shape[0]*df.shape[1] - df.shape[1]
    return res

def df_total(df):
    res = df.shape[0]*df.shape[1] - 1
    return res
    
    

df_between = df_between(df)
df_within = df_within(df)
df_total = df_total(df)

# Values to print
df_between
df_within
df_total

20

One thing you'll notice and that's always true (if you find different results, you probably got your calculus wrong...):
- dfbetween+dfwithin = dftotal

***Now the next step is to "state the decision rule"***
- basically we need to use df_between and df_within to lookup the critical value. Like I said above, the statistics we'll calculate will have to be greater than that critical value to reject H_0     
- here dfbetween = 2 and dfwithin = 18 like we've seen above... we'll just look those values up in the F table.. (2:44 in the yt vid...)     
- So with our "critical value" being 3.5546, we can say that if F (the stat we'll calculate below) is greater than 3.5546, we'll be able to reject the null hypothesis

In [25]:
# Let's start filling out our tab with the values already calculated above:
df2 = pd.DataFrame({'SS':[" "," "," "], 'df':[" "," "," "], 'MS':[" "," "," "], 'F':[" "," "," "]}, index = ["Between", "Within", "Total"])
df2.df = [df_between,df_within,df_total]
df2

        SS  df MS  F
Between      2
Within      18
Total       20

In [26]:
# Now the whole point is to calculate the remaining ones in order to finally get to the F statistic we're looking for
# Knowing the equations for the SS (Sum of Squares) Between/Within/Total (maybe find a picture or something...) I just wrote the following 3 functions:


def get_SS_between(df):
    N = 0
    col_sums = []
    sum_all_values_in_df =0
    sum_all_values_squared_in_df = 0
    n = len(df)
    for i in range(len(df.columns)):
        col = df.iloc[:, i]
        col_sum = col.sum()
        N = N+len(col)
        col_sums.append(col_sum)
    for i in range(len(col_sums)):
        sum_all_values_in_df =col_sums[i]+ sum_all_values_in_df
        sum_all_values_squared_in_df = np.square(col_sums[i])+ sum_all_values_squared_in_df
    SS_between = (sum_all_values_squared_in_df/n) - np.square(sum_all_values_in_df)/N
    return SS_between
    
SS_between = get_SS_between(df)
SS_between = round(SS_between, 2)

def get_SS_within(df):
    N = 0
    col_sums = []
    sum_all_values_squared_in_df = 0
    squared_individual_values = np.square(df.values)
    tot_squared_individual_values = 0
    n = len(df)
    for i in range(len(df.columns)):
        col = df.iloc[:, i]
        col_sum = col.sum()
        N = N+len(col)
        col_sums.append(col_sum)
    for i in range(len(col_sums)):
        sum_all_values_squared_in_df = np.square(col_sums[i])+ sum_all_values_squared_in_df
    res_temp = sum_all_values_squared_in_df/n
    for i in squared_individual_values:
        tot_squared_individual_values = i + tot_squared_individual_values
    SS_Within = tot_squared_individual_values.sum() - res_temp
    return SS_Within

SS_within = get_SS_within(df)
SS_within = round(SS_within, 2)

def get_SS_total(df):
    N = 0
    col_sums = []
    sum_all_values_in_df =0
    squared_individual_values = np.square(df.values)
    tot_squared_individual_values = 0
    n = len(df)
    for i in range(len(df.columns)):
        col = df.iloc[:, i]
        col_sum = col.sum()
        N = N+len(col)
        col_sums.append(col_sum)
    for i in range(len(col_sums)):
        sum_all_values_in_df =col_sums[i]+ sum_all_values_in_df
    res_temp = np.square(sum_all_values_in_df)/N
    for i in squared_individual_values:
        tot_squared_individual_values = i + tot_squared_individual_values
    SS_total = tot_squared_individual_values.sum() - res_temp
    return SS_total

SS_total = get_SS_total(df)
SS_total = round(SS_total, 2)

# Values to print out...
SS_between
SS_within
SS_total

# Alright, let's just fill up those values into our tab from above:
df2.SS = [SS_between,SS_within,SS_total]
df2

             SS  df MS  F
Between   98.67   2
Within    10.29  18
Total    108.95  20

In [27]:
# To get the values of the remaining column: "M of Squares", we just need to divide the Sum of Square values by the corresponding degrees of freedom:
# so we'd just get here:
df2.MS = df2.SS / df2.df
df2.MS = df2.MS.round(2)
df2

             SS  df     MS  F
Between   98.67   2  49.34
Within    10.29  18   0.57
Total    108.95  20   5.45

In [28]:
# We usually don't fill out the MS total value... so let me just remove it..
df2.loc["Total", "MS"] = ""
df2

             SS  df     MS  F
Between   98.67   2  49.34
Within    10.29  18   0.57
Total    108.95  20

In [30]:
# We're finally reaching the end!! The only thing left is to get our F value! Don't pay attention to the fact that there also are 3 rows in F, we're just going to fill the first one...
# F is equal to MS Between/MS Within. So we'd have:

df2.loc["Between", "F"] = round(df2.loc["Between", "MS"] / df2.loc["Within", "MS"], 2)
df2

             SS  df     MS      F
Between   98.67   2  49.34  86.56
Within    10.29  18   0.57
Total    108.95  20

### Conclusion
Now that we have our F statistic, the idea is to compare it to the critical value using the right distribution.
we can just conclude by saying that our F value is far beyond our critical value, so we can easily reject H_0 and say that the 3 means are not equal.

### A cleaner way of concluding would be: 
- "the three conditions differed significantly on anxiety level 
- "Mathematically" we'd have: F(2,18) = 86.56, p<0.05

### Disclaimer: 
Watch out, this test only allows us to say that these 3 groups are different "somehow", we can't tell what actually makes them different. To figure that out, we'd have to perform a "post hoc" test..

# ANOVA: Exercise 2

For this second example, we're considering 3 samples of employees whom stress level is measured (let's say on a  scale from 1 to 10..). 
- A first sample of employees under normal circumstances
- A second sample of employees after having announced layoffs 
- A finally a third sample of employees during layoffs

The 3 sample are samples of 5 individuals. And we want to measure the impact of the announced layoffs. 

using alpha = 0.05.

(Source: [YouTube Course](https://www.youtube.com/watch?v=-yQb_ZJnFXw#))

[TO DO ]: Maybe add a picture from the yt video to illustrate a lil bit... just so it looks nice.. aight?

In [31]:
# First step: like we did before: create the dataset:
dfExample2 = pd.DataFrame({'Normal':[2,3,7,2,6] , 'Announced Layoffs':[10,8,7,5,10] , 'During Layoffs':[10,13,14,13,15]})
dfExample2

   Normal  Announced Layoffs  During Layoffs
0       2                 10              10
1       3                  8              13
2       7                  7              14
3       2                  5              13
4       6                 10              15

In [ ]:
# Little challenge here, create one "super function" that'll create and fill up the tab to calculate the f stat all at once:

def calculateFStat(df):
    
    return FStat

In [ ]:
# Here's an example you can work on A lot of colors in this example, so I want you to do it lol: https://www.youtube.com/watch?v=-yQb_ZJnFXw
# Among the things you can do/should do: 
    # Always try your best to not just give numerical values but justications using "ground rules"    
    # create the small datasets he uses in her examples
    # calculate stats on em like variance, mean, and stuff like that like in the tea video
    # take notes about stuff he says in the video (based on what she says in the tea video)
    # ...
    # Again, what I want you to do on it is the same as what you did below for the tea exercise...

In [72]:
# Now here's the second exercise about anova
# part 1 from this vid: https://www.youtube.com/watch?v=tjolTrwJhjM
# putain c bien de la merde ca en fait... bon en gros, on considere le jeu de donnnes suivant:
# quand tu mettras au propore tu ecris aussi l'enonce que l'on suit ok?
    # on suppose que l'on test l'effet de 3 aliments sur un echantillon issue d'une population de personnes...
    # chaque colonne decrit les resultats obtenus par les personnes pour un aliment donne
    # avec ces resultats experimentaux, state wether or not those aliments have an effect on people (knowing that alpha = 10%)
    
# On pose les hypotheses:
    # H0: aucun des aliments n'a pas d'impacts sur les populations 
    # et les differences de moyenne observees ne sont pas assez significatives pour deduire d'un quelquonque effet du aux aliments...

    # H1: les aliments ont impact, les 3 moyennes different de facon suffisamment significative de la moyenne de la population pour imputer ces differences aux aliments

# Ok, travail preparatoire realise... c'est tipar!!
# -------------------------------------------------
# Definition du dataset (c'est vraiment un dataset bidon lol, jsuis dsl, je reprend l'ex de la video...)
df = pd.DataFrame({'Aliment 1':[3,2,1], 'Aliment 2':[5,3,4], 'Aliment 3':[5,6,7]} , index=np.arange(start=0, stop=3, step=1)) 
df

# Now we can calculate X-bar-bar meaning the mean of ALL the values in the dataframe (among all the columns, not per columns, among all of 'em)
def get_x_bar_bar_value(df):
    df_nbitems = 0
    col_sums = []
    sum_all_values_in_df =0
    for i in range(len(df.columns)):
        col = df.iloc[:, i]
        col_sum = col.sum()
        df_nbitems = df_nbitems+len(col)
        col_sums.append(col_sum)
    for i in range(len(col_sums)):
        sum_all_values_in_df = col_sums[i]+ sum_all_values_in_df
    x_bar_bar_value = sum_all_values_in_df/df_nbitems
    return x_bar_bar_value

x_bar_bar = get_x_bar_bar_value(df)
print("x_bar_bar = " + str(x_bar_bar))

# We can also calculate what is called SCT "somme des carres totaux" in French 
# it's basically calculate the 'variance' among all the column in the dataset using x_bar_bar as average
# So we'd have:

def get_SCT(x_bar_bar, df):
    SCT = 0
    for i in range(len(df.columns)):
        col = df.iloc[:, i]
        for i in range(len(col)):
            SCT = np.square(col[i]-x_b_b) + SCT
    return SCT
        
SCT = get_SCT(x_bar_bar, df)
print("SCT = " + str(SCT))


# We can also calculate what is called SC_intraclass 
# it looks like SCT value calculated above, but instead of using x_bar_bar, you wanna use the average value of each column
# So we'd have:

def get_SC_intra(df):
    SC_intra = 0
    for i in range(len(df.columns)):
        col = df.iloc[:, i]
        col_avg = col.sum()/len(col)
        for i in range(len(col)):
            SC_intra = np.square(col[i]-col_avg)+SC_intra
    return SC_intra 

SC_intra = get_SC_intra(df)
print("SC_intra = " + str(SC_intra))
    
# We can also calculate what is called SC_interclass 
# it looks like the 2 previous things seen above, but here, you wanna use the average of each column and x_bar_bar
# So we'd have:

def get_SC_inter(df, x_bar_bar):
    SC_inter = 0
    for i in range(len(df.columns)):
        col = df.iloc[:, i]
        col_avg = col.sum()/len(col)
        SC_inter = (np.square(col_avg-x_bar_bar)*len(col))+SC_inter
    return SC_inter 

SC_inter = get_SC_inter(df, x_bar_bar)
print("SC_inter = " + str(SC_inter))

# Rajoute une petite section de texte dans laquelle tu viens simplement ecrire la relation entre ces 3 petites values...

x_bar_bar = 4.0
SCT = 30.0
SC_intra = 6.0
SC_inter = 24.0

In [85]:
# variable suit une loi F. Dans l'exemple precedent du test d'hypothese "one sample test", la variable aleatoire etudiee suit une loi Z
# donc on a calcule le valeur de z associe a sa moyenne pour voir si cette valeur correspondait a une valeur "extreme" de la distribution Z
# valeur extreme si au dela du seuil alpha...

# on fait la memem chose ici: a savoir, on sait que les variables etudiees (qui sont 3 instances de la meme variable en fait...) suivent la meme loi F
# on calcul cette valeur de F. Puis en se servant de la table de F on voit si la valeur calculee s'avere etre une valeur extreme de cette f distribution
# sachant qu'encore une fois, valeur extreme ssi, au dela de ce qui est fixe par alpha (ici 10%)

# la formule donnant la valeur de f est la suivante:
# F=((SC_intra)/m-1) / ((SC_inter)/m(n-1))
# so we'd have in this example: 

def get_F_value(SC_intra, SC_inter, df):
    F = (SC_inter/(len(df.columns)-1)) / (SC_intra/(len(df.columns)*(len(df)-1)))
    return F

F = get_F_value(SC_intra, SC_inter, df)
print("F value = " + str(F))

F value = 12.0

In [87]:
# [TO BE DONE]Now the idea is simply to look up in the F table and using the alpha value guess if F we found is in critical region
# [TO BE DONE]Here's how you can plot f : http://pytolearn.csd.auth.gr/d1-hyptest/11/f-distro.html
    # it might require from you a lil bit of research lol anyways... then just use the video to explain how to use it...
    # last vid around (13:30)

In [3]:
# Below are extra exercises about anova my friend... knock yourself out brotha!!

# Among the things you can do/should do: 
    # Always try your best to not just give numerical values but justications using "ground rules"    
    # create the small datasets thye use in their examples
    # calculate stats on em like variance, mean, and stuff like that like in the tea video
    # take notes about stuff he says in the video (based on what she says in the tea video)
    # ...
    # Again, what I want you to do on it is the same as what you did below for the tea exercise...
    


    

# Here's an example you can work on (tea exercise...): https://www.youtube.com/watch?v=srDr-4cz1KI&feature=emb_logo
# Here's the corresponding course: https://www.statisticshowto.com/probability-and-statistics/hypothesis-testing/anova/    
# Among the things you can do/should do: 
    # Always try your best to not just give numerical values but justications using "ground rules"
    # create the small datasets she uses in her examples
    # calculate stats on em like variance, mean, and stuff like that
    # take notes about stuff she says in the video
    # ...
    
# Here's another example you can work on: https://www.youtube.com/watch?v=ITf4vHhyGpc
    # What you'll do on this is pretty much the same thing as what you did above...
    
# Here's another example: https://www.youtube.com/watch?v=lZFmFuZGQTk
    # This one is about the 2 way anova... so you do whatever you can tho aight??...

# The last one, also interesting: https://www.youtube.com/watch?v=WUjsSB7E-ko
    # Same as above...
    
# Here's something else you can work on after you're done with this: http://pytolearn.csd.auth.gr/d1-hyptest/11/f-distro.html
    # its the student blog lol, just do the same things you're doing below...
    
# Here are other example you can work on (from khan academy, veeery interesting...): 
    # Part 1: https://www.youtube.com/watch?v=tjolTrwJhjM
    # Part 2: https://www.youtube.com/watch?v=DMo9yofC5C8
    # Part 3: https://www.youtube.com/watch?v=y8nRhsixBPs

In [1]:
# And finally one thing you can do is go through the course material of guyader once you feel like you're good enough...

# Student

In [ ]:
# To explain student just follow along with this exercise: 
# https://www.youtube.com/watch?v=VPd8DOL13Iw&list=PL568547ACA9211CCA&index=62

In [ ]:
# On considere l'exemple de la video suivante: https://www.youtube.com/watch?v=KGtGgyqKzGQ
    # On mesure le taux d'emission d'un echantillon voitures. pour etre conforme aux nouvelles reglementations, ces voitures doivent emettre moins qu'un seuil fixe a 20ppm
    # Au regard des resultats du test auquel on soumet ces voitures, peut on dire que c'est le cas?
    # alpha est fixe a 0.01
    # D'autre questions que je me suis pose:
        # [TO BE DONE]Si avec une taille d'echantillon donne, un niveau de confiance alpha donne il etait possible de fixer sans resultat, le seuil au dessous duquel si l'echantillon produit des resultat inferieurs, on pourrait dire avec une confiance de n% que le test est successful
        # [TO BE DONE]Si qqn viens avec des resultats d'echantillons me demander "C'est bon ca passe??" quelles quesitons pernitentes je dois me poser afin de valider ou non le test de ce quidam? (bien sur j'imagine que taille de l'echantillon et resultats experimentaux sont necessaires, mais n'ais je pas besoin d'au moins une donnee sur la population?)
    

# Set the test parameters:
# H_0: Non, les voitures ne sont pas conformes. Les resultats obtenus ne sont pas assez situes dans les regions extremes de la distribution des moyenne pour pouvoir ecarter la possibilite qu'il soient simplement du a la variabilite de la mesure/le hasard.
    # On aurait alors: mu = 2- ppm
# H_1: Oui, les moteurs sont bien conformes. Les resultats, pour cette taille d'echantillon sont suffisamment extremes pour etre certain qu'il ne sont pas du au hasard...
    # On a alors: H_1 mu<20ppm   
# The sample statistics:
    # X_bar = 17,17
    # s = 2.98
# After first quick analysis, we can say that: 
    # we'll reject H_0 if P(x_bar == 17,17/H_0 vrai)<= 0.01
    # In plain english it'd be: "Having these sample statistics for a sample of this size with a population that doesn't pass this test is nearly impossible"
    # In other words making une erreur de premiere espece (rejeter H_0 alors qu'elle est vraie est quasi impossible)    
# Let's perform this test as usual:
    # we'll take a look at the distribution of sample means and try to see which law it follows
    # then'll we'll calculate the law statistic (here the statistic t) and see if this statistic is in extreme regions

In [27]:
# This sample is a small sample (n<30) so the statistic we'll calculate is a T statistic, and it follows a student law
# We have t = (x_bar - mu_xbar)/(s/sqrt(n)), we know/can easily calculate the following values:
    # x_bar
    # mu_xbar which is equal to 20 since we're considering H_0 to be true for now
    # and n the sample size of 10
    
# We set mu = 20 as discussed above...
mu = 20
# How you create a Series
series = pd.Series([15.6, 16.2, 22.5, 20.5, 16.4, 19.4, 16.6, 17.9, 12.7, 13.9] , index=np.arange(start=0, stop=10, step=1)) 
series.index = [0,1,2,3,4,5,6,7,8,9] #If you wanna modify index values
s = series.std()
x_bar = series.mean()
n = len(series)
T = (x_bar - mu)/(s/np.sqrt(n))


print("The standard deviation s: " + str(s))
print("The sample mean x_bar:" + str(x_bar))
print("The sample size n: " + str(n))
print("The statistics T:" + str(T))

# again as explain above, because of its calculation, this staticstics T should follow a normal law, but, because we're on a small dataset, we'll use a different law, the distribuiton we use is still the normal distribution.
# But depending on parameters such as the "degre de liberte" (size-1 = 9 here) and... we'll simply use a different table, that'll take in account the small size of sample in probability calculus
# Here's how we're going to use this table

The standard deviation s: 2.9814426038413018
The sample mean x_bar:17.169999999999998
The sample size n: 10
The statistics T:-3.001649525885985

In [ ]:
# [TO BE DONE]Like for Anova the idea is simply to look up in the T table and using the alpha value (and the "degre de liberte" previously calculated) guess if T we found is in critical region
# [TO BE DONE]Here's how you can use the T table in the video https://www.youtube.com/watch?v=KGtGgyqKzGQ (it's around 10:00)
# Watch out, you want to formulate your findings in the following way:
        # pour un seuil de tolerance alpha = 0.01, on cherche la region pour laquelle la probabilite d'avoir des valeurs en dehors de cette region est de 99%
        # in other words, we want to have 1 % of the values in our critical region and check if our T stat is in these 1 %
        
# You already know that we'll reject this H_0 thinggy...

In [2]:
# Here's something else you can work on after you're done with this: http://pytolearn.csd.auth.gr/d1-hyptest/12/ttest-indep.html
    # its the student blog lol, just do the same things you're doing below...

# Here's an example you can work on (from khan academy francophone): https://www.youtube.com/watch?v=KGtGgyqKzGQ
# Here's the corresponding course: https://www.youtube.com/watch?v=f7gfCutYXbU
# Among the things you can do/should do: 
    # Always try your best to not just give numerical values but justications using "ground rules"
    # create the small datasets he uses in her examples
    # calculate stats on em like variance, mean, and stuff like that (like in the tea video from the anova part)
    # take notes about stuff he says in the video (based on what she did in the tea video from the anova part)
    # ...


# Hey, can you take a look at this before doing anything else?
    # Interval de confiance (Student): https://www.youtube.com/watch?v=i5DmLO1wVqQ


# Here's an example you can work on (tea exercise...): https://www.youtube.com/watch?v=fKZA5waOJ0U&feature=emb_logo
# Here's the corresponding course: https://www.statisticshowto.com/probability-and-statistics/t-test/    
# Among the things you can do/should do: 
    # Always try your best to not just give numerical values but justications using "ground rules"
    # create the small datasets she uses in her examples
    # calculate stats on em like variance, mean, and stuff like that
    # take notes about stuff she says in the video
    # ...
    
# Here's a final example I want you to work on:
    # part 1 ("interval de confiance" stuff...): https://www.youtube.com/watch?v=sXV1GOVpGsY 
    # part 2 (actual hypothesis testing): https://www.youtube.com/watch?v=Sl5g5_w7HU4
# Eventhough it's not a t-test, I like this example, it's a 2 sample comparison on which you wont use the T test, but the z test seen previously...
# What I want you to understand with this, is that: 
    # there's no such thing as t, or z, or x,y,z test I think... 
    # I think it's more about the information you have in the enonce that you'll know what kind of formula you'll use to calculate the probability you're looking for
    # And based on the same enonce, you'll know which normal law table to use ("is it a z table?", "is it a t table?", ...).
    # Rephrasing the above: "And based on the enonce, you'll know which law does the variable follows..."
    # This a conclusion you can even put in the "Summary of all kind of testing" notebook...

In [ ]:
# To do: 
# Maybe inverser l'ordre de anova and student test.. since anova allows "more" than t test... anyways, not super important...

In [ ]:
# Annexes:
# [in case you really need a course...]: 
    # https://www.youtube.com/watch?v=FPqeVhtOXEo 
# [nice interesting other course...]: 
    # https://www.youtube.com/watch?v=OypCNBPmGBY